# Generated by Django 5.2.6 on 2025-11-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
