# Generated by Django 5.2.6 on 2025-11-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadDifusion_Producto',
        ),
    ]
