# Generated by Django 5.2.6 on 2025-11-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_delete_actividaddifusion_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoasociado',
            name='proyecto',
        ),
    ]
